// `landed://` is how the browser reaches the app WITHOUT a localhost port: the OS routes the URL,
// so there is no origin, no CORS, and no mixed-content question. The flip side is that anything on
// the web can navigate to one — a link, an iframe, an ad — so a deep link is untrusted input that
// arrives with the user's own privileges. This parser is the gate, and these tests are its spec.
import { test } from "node:test";
import assert from "node:assert/strict";
import { parseDeepLink } from "../desktop/src/deeplink";
import { deepLink } from "@landed/shared/desktop/deeplink";

test("reveal targets parse into a kind and an argument", () => {
  assert.deepEqual(parseDeepLink("landed://reveal/assets"), { action: "reveal", target: { kind: "assets" } });
  assert.deepEqual(parseDeepLink("landed://reveal/resume/acme"), {
    action: "reveal",
    target: { kind: "resume", slug: "acme" },
  });
  assert.deepEqual(parseDeepLink("landed://reveal/prep/acme"), {
    action: "reveal",
    target: { kind: "prep", slug: "acme" },
  });
});

test("decoding happens once, before validation — an encoded separator cannot sneak through", () => {
  // Slugs are generated by backend/src/db/prep.ts:311 as [a-z0-9-]+, so anything outside that set
  // is not a slug this app ever produced. A space is harmless in itself but is not one of ours,
  // and the narrow set is what makes "refuse, don't sanitise" cheap to enforce.
  assert.equal(parseDeepLink("landed://reveal/resume/acme%20corp"), null);
  assert.deepEqual(parseDeepLink("landed://reveal/resume/acme-corp"), {
    action: "reveal",
    target: { kind: "resume", slug: "acme-corp" },
  });
});

test("the agent view is addressable, optionally by run type", () => {
  assert.deepEqual(parseDeepLink("landed://agent"), { action: "agent", type: null });
  assert.deepEqual(parseDeepLink("landed://agent/tailoring"), { action: "agent", type: "tailoring" });
});

test("a foreign scheme is refused — only landed:// is ours", () => {
  assert.equal(parseDeepLink("https://evil.example/reveal/assets"), null);
  assert.equal(parseDeepLink("file:///etc/passwd"), null);
  assert.equal(parseDeepLink("landedx://reveal/assets"), null);
});

test("traversal and separators in a slug are refused, not sanitised", () => {
  // Refused rather than stripped: a cleaned-up slug still resolves to SOME folder, and quietly
  // revealing the wrong one is worse than doing nothing.
  for (const bad of [
    "landed://reveal/resume/../../etc",
    "landed://reveal/resume/%2e%2e%2fetc",
    "landed://reveal/resume/a%2fb",
    "landed://reveal/resume/a/b",
    "landed://reveal/resume/",
  ]) {
    assert.equal(parseDeepLink(bad), null, bad);
  }
});

test("unknown actions and malformed input are null, never a throw", () => {
  for (const bad of ["landed://exfiltrate/everything", "landed://reveal/unknown/x", "landed://", "not a url", ""]) {
    assert.equal(parseDeepLink(bad), null, JSON.stringify(bad));
  }
});

test("every builder round-trips through the parser — the two halves cannot drift", () => {
  // The builders ship to the browser (shared/) and the parser runs in the desktop app (desktop/).
  // Nothing at runtime checks that they agree about a string crossing an OS boundary, so this does.
  assert.deepEqual(parseDeepLink(deepLink.revealAssets()), { action: "reveal", target: { kind: "assets" } });
  assert.deepEqual(parseDeepLink(deepLink.revealResume("acme-corp")), {
    action: "reveal",
    target: { kind: "resume", slug: "acme-corp" },
  });
  assert.deepEqual(parseDeepLink(deepLink.revealPrep("acme-corp")), {
    action: "reveal",
    target: { kind: "prep", slug: "acme-corp" },
  });
  assert.deepEqual(parseDeepLink(deepLink.agent()), { action: "agent", type: null });
  assert.deepEqual(parseDeepLink(deepLink.agent("tailoring")), { action: "agent", type: "tailoring" });
});
