// AUTO-GENERATED by scripts/gen (extracted from the agent prep artifacts).
// Edit the source artifacts + re-run, or hand-edit carefully. Consumed by scripts/seed-prep.ts.
import type { PrepContent, PrepPlan } from "@landed/backend/db/prep";

export type PrepSeed = {
  id: string;
  track: "coding" | "system_design";
  name: string;
  prompt?: string;
  difficulty?: string;
  priority?: string;
  url?: string;
  leetcodeNum?: number;
  tags: string[];
  companies: string[];
  content: PrepContent;
  plan?: PrepPlan;
  sortOrder: number;
};

export const PREP_SEED: PrepSeed[] = [
  {
    "id": "lc-1",
    "track": "coding",
    "name": "Two Sum",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/two-sum/",
    "leetcodeNum": 1,
    "tags": [
      "Hash Map / Frequency"
    ],
    "companies": [],
    "content": {
      "note": "Store complement in map as you iterate. O(n). Don't sort — need original indices."
    },
    "plan": {
      "day": 1,
      "week": 1,
      "pattern": "Hash Map / Frequency",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 0
  },
  {
    "id": "lc-242",
    "track": "coding",
    "name": "Valid Anagram",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/valid-anagram/",
    "leetcodeNum": 242,
    "tags": [
      "Hash Map / Frequency"
    ],
    "companies": [],
    "content": {
      "note": "Frequency count with map or array[26]. Compare counts."
    },
    "plan": {
      "day": 1,
      "week": 1,
      "pattern": "Hash Map / Frequency",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 1
  },
  {
    "id": "lc-49",
    "track": "coding",
    "name": "Group Anagrams",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/group-anagrams/",
    "leetcodeNum": 49,
    "tags": [
      "Hash Map / Frequency"
    ],
    "companies": [],
    "content": {
      "note": "Key = sorted string. Group by key in map."
    },
    "plan": {
      "day": 1,
      "week": 1,
      "pattern": "Hash Map / Frequency",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 2
  },
  {
    "id": "lc-560",
    "track": "coding",
    "name": "Subarray Sum Equals K",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/subarray-sum-equals-k/",
    "leetcodeNum": 560,
    "tags": [
      "Hash Map / Frequency"
    ],
    "companies": [],
    "content": {
      "note": "Prefix sum + map. count[0]=1 init critical."
    },
    "plan": {
      "day": 1,
      "week": 1,
      "pattern": "Hash Map / Frequency",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 3
  },
  {
    "id": "lc-215",
    "track": "coding",
    "name": "Kth Largest Element",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/kth-largest-element-in-an-array/",
    "leetcodeNum": 215,
    "tags": [
      "Heap / Priority Queue"
    ],
    "companies": [],
    "content": {
      "note": "Min-heap of size k. Top = kth largest. Know quickselect too."
    },
    "plan": {
      "day": 2,
      "week": 1,
      "pattern": "Heap / Priority Queue",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 4
  },
  {
    "id": "lc-347",
    "track": "coding",
    "name": "Top K Frequent Elements",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/top-k-frequent-elements/",
    "leetcodeNum": 347,
    "tags": [
      "Heap / Priority Queue"
    ],
    "companies": [],
    "content": {
      "note": "Freq map → min-heap. Or bucket sort O(n)."
    },
    "plan": {
      "day": 2,
      "week": 1,
      "pattern": "Heap / Priority Queue",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 5
  },
  {
    "id": "lc-23",
    "track": "coding",
    "name": "Merge K Sorted Lists",
    "difficulty": "Hard",
    "url": "https://leetcode.com/problems/merge-k-sorted-lists/",
    "leetcodeNum": 23,
    "tags": [
      "Heap / Priority Queue"
    ],
    "companies": [],
    "content": {
      "note": "THE k-way merge. Include list idx in heap tuple."
    },
    "plan": {
      "day": 2,
      "week": 1,
      "pattern": "Heap / Priority Queue",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 6
  },
  {
    "id": "lc-295",
    "track": "coding",
    "name": "Find Median from Data Stream",
    "difficulty": "Hard",
    "url": "https://leetcode.com/problems/find-median-from-data-stream/",
    "leetcodeNum": 295,
    "tags": [
      "Heap / Priority Queue"
    ],
    "companies": [],
    "content": {
      "note": "Two heaps. Rebalance after every insert."
    },
    "plan": {
      "day": 2,
      "week": 1,
      "pattern": "Heap / Priority Queue",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 7
  },
  {
    "id": "lc-76",
    "track": "coding",
    "name": "Minimum Window Substring",
    "difficulty": "Hard",
    "url": "https://leetcode.com/problems/minimum-window-substring/",
    "leetcodeNum": 76,
    "tags": [
      "Sliding Window"
    ],
    "companies": [],
    "content": {
      "note": "Two freq maps. 'formed' counter."
    },
    "plan": {
      "day": 3,
      "week": 1,
      "pattern": "Sliding Window",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 8
  },
  {
    "id": "lc-3",
    "track": "coding",
    "name": "Longest Substring Without Repeating",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/longest-substring-without-repeating-characters/",
    "leetcodeNum": 3,
    "tags": [
      "Sliding Window"
    ],
    "companies": [],
    "content": {
      "note": "Variable window. Set tracks chars. Shrink while duplicate."
    },
    "plan": {
      "day": 3,
      "week": 1,
      "pattern": "Sliding Window",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 9
  },
  {
    "id": "lc-424",
    "track": "coding",
    "name": "Longest Repeating Character Replacement",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/longest-repeating-character-replacement/",
    "leetcodeNum": 424,
    "tags": [
      "Sliding Window"
    ],
    "companies": [],
    "content": {
      "note": "Valid if (windowLen - maxFreq) <= k."
    },
    "plan": {
      "day": 3,
      "week": 1,
      "pattern": "Sliding Window",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 10
  },
  {
    "id": "lc-567",
    "track": "coding",
    "name": "Permutation in String",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/permutation-in-string/",
    "leetcodeNum": 567,
    "tags": [
      "Sliding Window"
    ],
    "companies": [],
    "content": {
      "note": "Fixed window = len(s1). 'matches' counter for O(1) per step."
    },
    "plan": {
      "day": 3,
      "week": 1,
      "pattern": "Sliding Window",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 11
  },
  {
    "id": "lc-704",
    "track": "coding",
    "name": "Binary Search",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/binary-search/",
    "leetcodeNum": 704,
    "tags": [
      "Binary Search"
    ],
    "companies": [],
    "content": {
      "note": "Nail the template. lo+(hi-lo)//2 avoids overflow."
    },
    "plan": {
      "day": 4,
      "week": 1,
      "pattern": "Binary Search",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 12
  },
  {
    "id": "lc-34",
    "track": "coding",
    "name": "Find First and Last Position",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/",
    "leetcodeNum": 34,
    "tags": [
      "Binary Search"
    ],
    "companies": [],
    "content": {
      "note": "Biased-left (hi=mid when found) and biased-right (lo=mid+1)."
    },
    "plan": {
      "day": 4,
      "week": 1,
      "pattern": "Binary Search",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 13
  },
  {
    "id": "lc-33",
    "track": "coding",
    "name": "Search in Rotated Sorted Array",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/search-in-rotated-sorted-array/",
    "leetcodeNum": 33,
    "tags": [
      "Binary Search"
    ],
    "companies": [],
    "content": {
      "note": "One half always sorted. Check if target in sorted half."
    },
    "plan": {
      "day": 4,
      "week": 1,
      "pattern": "Binary Search",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 14
  },
  {
    "id": "lc-875",
    "track": "coding",
    "name": "Koko Eating Bananas",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/koko-eating-bananas/",
    "leetcodeNum": 875,
    "tags": [
      "Binary Search"
    ],
    "companies": [],
    "content": {
      "note": "Answer space BS. canFinish(speed) monotonic."
    },
    "plan": {
      "day": 4,
      "week": 1,
      "pattern": "Binary Search",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 15
  },
  {
    "id": "lc-200",
    "track": "coding",
    "name": "Number of Islands",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/number-of-islands/",
    "leetcodeNum": 200,
    "tags": [
      "Graphs / Union-Find"
    ],
    "companies": [],
    "content": {
      "note": "Flood fill. Mark visited in-place. BFS or DFS."
    },
    "plan": {
      "day": 5,
      "week": 1,
      "pattern": "Graphs / Union-Find",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 16
  },
  {
    "id": "lc-207",
    "track": "coding",
    "name": "Course Schedule",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/course-schedule/",
    "leetcodeNum": 207,
    "tags": [
      "Graphs / Union-Find"
    ],
    "companies": [],
    "content": {
      "note": "Topological sort. len(result)==n → no cycle."
    },
    "plan": {
      "day": 5,
      "week": 1,
      "pattern": "Graphs / Union-Find",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 17
  },
  {
    "id": "lc-684",
    "track": "coding",
    "name": "Redundant Connection",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/redundant-connection/",
    "leetcodeNum": 684,
    "tags": [
      "Graphs / Union-Find"
    ],
    "companies": [],
    "content": {
      "note": "Union-Find. First edge joining already-connected nodes."
    },
    "plan": {
      "day": 5,
      "week": 1,
      "pattern": "Graphs / Union-Find",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 18
  },
  {
    "id": "lc-399",
    "track": "coding",
    "name": "Evaluate Division",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/evaluate-division/",
    "leetcodeNum": 399,
    "tags": [
      "Graphs / Union-Find"
    ],
    "companies": [],
    "content": {
      "note": "Weighted graph BFS. Build a/b and b/a edges."
    },
    "plan": {
      "day": 5,
      "week": 1,
      "pattern": "Graphs / Union-Find",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 19
  },
  {
    "id": "lc-15",
    "track": "coding",
    "name": "3Sum",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/3sum/",
    "leetcodeNum": 15,
    "tags": [
      "Two Pointers"
    ],
    "companies": [],
    "content": {
      "note": "Sort. Fix one, two-pointer rest. Skip dupes at all 3 levels."
    },
    "plan": {
      "day": 6,
      "week": 1,
      "pattern": "Two Pointers",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 20
  },
  {
    "id": "lc-11",
    "track": "coding",
    "name": "Container With Most Water",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/container-with-most-water/",
    "leetcodeNum": 11,
    "tags": [
      "Two Pointers"
    ],
    "companies": [],
    "content": {
      "note": "Move the shorter side — taller side can never increase area."
    },
    "plan": {
      "day": 6,
      "week": 1,
      "pattern": "Two Pointers",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 21
  },
  {
    "id": "lc-141",
    "track": "coding",
    "name": "Linked List Cycle",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/linked-list-cycle/",
    "leetcodeNum": 141,
    "tags": [
      "Two Pointers"
    ],
    "companies": [],
    "content": {
      "note": "Slow/fast pointers. They meet if cycle exists."
    },
    "plan": {
      "day": 6,
      "week": 1,
      "pattern": "Two Pointers",
      "anchor": false,
      "extra": true
    },
    "sortOrder": 22
  },
  {
    "id": "lc-19",
    "track": "coding",
    "name": "Remove Nth Node From End",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/remove-nth-node-from-end-of-list/",
    "leetcodeNum": 19,
    "tags": [
      "Two Pointers"
    ],
    "companies": [],
    "content": {
      "note": "Gap of n between fast and slow. Dummy head handles edge cases."
    },
    "plan": {
      "day": 6,
      "week": 1,
      "pattern": "Two Pointers",
      "anchor": false,
      "extra": true
    },
    "sortOrder": 23
  },
  {
    "id": "lc-239",
    "track": "coding",
    "name": "Sliding Window Maximum",
    "difficulty": "Hard",
    "url": "https://leetcode.com/problems/sliding-window-maximum/",
    "leetcodeNum": 239,
    "tags": [
      "Stack / Monotonic"
    ],
    "companies": [],
    "content": {
      "note": "Monotonic decreasing deque. Expire from front (out-of-window), evict smaller from back, record front as max."
    },
    "plan": {
      "day": 7,
      "week": 1,
      "pattern": "Stack / Monotonic",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 24
  },
  {
    "id": "lc-739",
    "track": "coding",
    "name": "Daily Temperatures",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/daily-temperatures/",
    "leetcodeNum": 739,
    "tags": [
      "Stack / Monotonic"
    ],
    "companies": [],
    "content": {
      "note": "Monotonic decreasing stack of indices. Pop when warmer day found."
    },
    "plan": {
      "day": 7,
      "week": 1,
      "pattern": "Stack / Monotonic",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 25
  },
  {
    "id": "lc-84",
    "track": "coding",
    "name": "Largest Rectangle in Histogram",
    "difficulty": "Hard",
    "url": "https://leetcode.com/problems/largest-rectangle-in-histogram/",
    "leetcodeNum": 84,
    "tags": [
      "Stack / Monotonic"
    ],
    "companies": [],
    "content": {
      "note": "Monotonic increasing stack. Pop when shorter bar arrives — that's when you know both boundaries."
    },
    "plan": {
      "day": 7,
      "week": 1,
      "pattern": "Stack / Monotonic",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 26
  },
  {
    "id": "lc-102",
    "track": "coding",
    "name": "Binary Tree Level Order Traversal",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/binary-tree-level-order-traversal/",
    "leetcodeNum": 102,
    "tags": [
      "Trees / BFS / DFS"
    ],
    "companies": [],
    "content": {
      "note": "BFS template. level_size = len(queue) before inner loop."
    },
    "plan": {
      "day": 9,
      "week": 2,
      "pattern": "Trees / BFS / DFS",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 27
  },
  {
    "id": "lc-98",
    "track": "coding",
    "name": "Validate BST",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/validate-binary-search-tree/",
    "leetcodeNum": 98,
    "tags": [
      "Trees / BFS / DFS"
    ],
    "companies": [],
    "content": {
      "note": "Pass (min, max) bounds recursively — not just immediate children."
    },
    "plan": {
      "day": 9,
      "week": 2,
      "pattern": "Trees / BFS / DFS",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 28
  },
  {
    "id": "lc-235",
    "track": "coding",
    "name": "Lowest Common Ancestor of BST",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/",
    "leetcodeNum": 235,
    "tags": [
      "Trees / BFS / DFS"
    ],
    "companies": [],
    "content": {
      "note": "BST property: both left→go left, both right→go right, split→current."
    },
    "plan": {
      "day": 9,
      "week": 2,
      "pattern": "Trees / BFS / DFS",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 29
  },
  {
    "id": "lc-543",
    "track": "coding",
    "name": "Diameter of Binary Tree",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/diameter-of-binary-tree/",
    "leetcodeNum": 543,
    "tags": [
      "Trees / BFS / DFS"
    ],
    "companies": [],
    "content": {
      "note": "Postorder DFS. diameter = left_h + right_h. Track global max."
    },
    "plan": {
      "day": 9,
      "week": 2,
      "pattern": "Trees / BFS / DFS",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 30
  },
  {
    "id": "lc-146",
    "track": "coding",
    "name": "LRU Cache",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/lru-cache/",
    "leetcodeNum": 146,
    "tags": [
      "Design Problems"
    ],
    "companies": [],
    "content": {
      "note": "HashMap + DLL. O(1) get/put. Implement DLL yourself."
    },
    "plan": {
      "day": 10,
      "week": 2,
      "pattern": "Design Problems",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 31
  },
  {
    "id": "lc-362",
    "track": "coding",
    "name": "Design Hit Counter",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/design-hit-counter/",
    "leetcodeNum": 362,
    "tags": [
      "Design Problems"
    ],
    "companies": [],
    "content": {
      "note": "Deque of timestamps. Time-window pattern. Very DB."
    },
    "plan": {
      "day": 10,
      "week": 2,
      "pattern": "Design Problems",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 32
  },
  {
    "id": "lc-346",
    "track": "coding",
    "name": "Moving Average from Data Stream",
    "difficulty": "Easy",
    "url": "https://leetcode.com/problems/moving-average-from-data-stream/",
    "leetcodeNum": 346,
    "tags": [
      "Design Problems"
    ],
    "companies": [],
    "content": {
      "note": "Queue of size k + running sum. Streaming aggregation."
    },
    "plan": {
      "day": 10,
      "week": 2,
      "pattern": "Design Problems",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 33
  },
  {
    "id": "lc-380",
    "track": "coding",
    "name": "Insert Delete GetRandom O(1)",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/insert-delete-getrandom-o1/",
    "leetcodeNum": 380,
    "tags": [
      "Design Problems"
    ],
    "companies": [],
    "content": {
      "note": "HashMap + array. Swap-delete trick for O(1) random."
    },
    "plan": {
      "day": 10,
      "week": 2,
      "pattern": "Design Problems",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 34
  },
  {
    "id": "lc-56",
    "track": "coding",
    "name": "Merge Intervals",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/merge-intervals/",
    "leetcodeNum": 56,
    "tags": [
      "Intervals + Merge"
    ],
    "companies": [],
    "content": {
      "note": "Sort by start. Extend end if overlap."
    },
    "plan": {
      "day": 11,
      "week": 2,
      "pattern": "Intervals + Merge",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 35
  },
  {
    "id": "lc-57",
    "track": "coding",
    "name": "Insert Interval",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/insert-interval/",
    "leetcodeNum": 57,
    "tags": [
      "Intervals + Merge"
    ],
    "companies": [],
    "content": {
      "note": "Three passes: before, overlapping, after."
    },
    "plan": {
      "day": 11,
      "week": 2,
      "pattern": "Intervals + Merge",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 36
  },
  {
    "id": "lc-435",
    "track": "coding",
    "name": "Non-overlapping Intervals",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/non-overlapping-intervals/",
    "leetcodeNum": 435,
    "tags": [
      "Intervals + Merge"
    ],
    "companies": [],
    "content": {
      "note": "Greedy: sort by END. Keep earliest-ending. Count removals."
    },
    "plan": {
      "day": 11,
      "week": 2,
      "pattern": "Intervals + Merge",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 37
  },
  {
    "id": "lc-253",
    "track": "coding",
    "name": "Meeting Rooms II",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/meeting-rooms-ii/",
    "leetcodeNum": 253,
    "tags": [
      "Intervals + Merge"
    ],
    "companies": [],
    "content": {
      "note": "Min-heap of end times. Heap size = rooms needed."
    },
    "plan": {
      "day": 11,
      "week": 2,
      "pattern": "Intervals + Merge",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 38
  },
  {
    "id": "lc-198",
    "track": "coding",
    "name": "House Robber",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/house-robber/",
    "leetcodeNum": 198,
    "tags": [
      "Dynamic Programming"
    ],
    "companies": [],
    "content": {
      "note": "dp[i] = max(dp[i-1], dp[i-2] + nums[i]). Optimize to 2 vars."
    },
    "plan": {
      "day": 12,
      "week": 2,
      "pattern": "Dynamic Programming",
      "anchor": true,
      "extra": false
    },
    "sortOrder": 39
  },
  {
    "id": "lc-322",
    "track": "coding",
    "name": "Coin Change",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/coin-change/",
    "leetcodeNum": 322,
    "tags": [
      "Dynamic Programming"
    ],
    "companies": [],
    "content": {
      "note": "dp[0]=0, rest=inf. Unbounded knapsack template."
    },
    "plan": {
      "day": 12,
      "week": 2,
      "pattern": "Dynamic Programming",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 40
  },
  {
    "id": "lc-300",
    "track": "coding",
    "name": "Longest Increasing Subsequence",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/longest-increasing-subsequence/",
    "leetcodeNum": 300,
    "tags": [
      "Dynamic Programming"
    ],
    "companies": [],
    "content": {
      "note": "O(n²) dp. O(n log n) with patience sort."
    },
    "plan": {
      "day": 12,
      "week": 2,
      "pattern": "Dynamic Programming",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 41
  },
  {
    "id": "lc-1143",
    "track": "coding",
    "name": "Longest Common Subsequence",
    "difficulty": "Medium",
    "url": "https://leetcode.com/problems/longest-common-subsequence/",
    "leetcodeNum": 1143,
    "tags": [
      "Dynamic Programming"
    ],
    "companies": [],
    "content": {
      "note": "2D DP. Match→diagonal+1. No match→max(up, left)."
    },
    "plan": {
      "day": 12,
      "week": 2,
      "pattern": "Dynamic Programming",
      "anchor": false,
      "extra": false
    },
    "sortOrder": 42
  },
  {
    "id": "scenario-kway",
    "track": "coding",
    "name": "External K-Way Merge",
    "prompt": "Given K sorted arrays (representing pre-sorted chunks from disk), merge them into one sorted array efficiently. Memory budget: you can only hold O(K) elements at a time.",
    "difficulty": "Medium",
    "priority": "TOP",
    "tags": [
      "heap",
      "k-way-merge",
      "external-sort"
    ],
    "companies": [],
    "content": {
      "why": "A classic merge pattern that shows up in log/file compaction, external sorting, and streaming systems. Worth knowing cold.",
      "approach": [
        "Seed a min-heap with the first element from each of the K lists: (val, list_idx, element_idx)",
        "Pop the minimum, add to result, push next element from the same list",
        "Repeat until heap empty — O(n log K) time, O(K) space",
        "DO NOT do sequential pairwise merges — that's O(Kn) and misses the point entirely",
        "Include list_idx in tuple to break ties (avoid comparing incomparable objects)"
      ],
      "followUps": [
        "What if each chunk is on disk and too large to load fully into memory?",
        "How do you handle K=1000 sorted files? Same algorithm — heap size stays K.",
        "What if chunks have duplicate values across files? Merge naturally includes them.",
        "Extend to external sort: what's the full pipeline for sorting data that doesn't fit in RAM?"
      ],
      "gotchas": [
        "Always include source index in heap tuple: (val, list_idx, elem_idx) — never just (val, list_idx)",
        "Push the NEXT element from the same list immediately after popping — don't batch",
        "Edge: empty lists — skip them when seeding the heap"
      ]
    },
    "sortOrder": 43
  },
  {
    "id": "scenario-topk",
    "track": "coding",
    "name": "Top-K Frequent Keys in Log Stream",
    "prompt": "Given a stream of string events (or a large log file), return the K most frequent keys. Optimize for both time and memory. Follow-up: streaming version where you can't store all events.",
    "difficulty": "Medium",
    "priority": "TOP",
    "tags": [
      "heap",
      "hashmap",
      "streaming",
      "heavy-hitter"
    ],
    "companies": [],
    "content": {
      "why": "Analytics over billions of log events. Top-K with memory constraints is a bread-and-butter problem.",
      "approach": [
        "Batch version: Counter(stream) → heapq.nlargest(K, counts.items(), key=lambda x: x[1])",
        "Min-heap of size K: for each new (key, count) pair, push if count > heap[0][0], then pop if size > K",
        "Streaming with memory budget: use a size-K min-heap as a 'heavy hitter' tracker",
        "State complexity: O(K) for the heap vs O(n) for the full counter — articulate the trade-off",
        "Advanced: mention Count-Min Sketch for approximate heavy hitters with sub-linear memory"
      ],
      "followUps": [
        "What if the stream is infinite and you can't store all keys?",
        "How accurate is a size-K min-heap approach? When does it fail?",
        "What's the Count-Min Sketch approach and its error guarantees?",
        "Distributed version: each node has a shard. How do you merge top-K across nodes?"
      ],
      "gotchas": [
        "Heap tracks (count, key) not (key, count) — you compare by count",
        "Python heapq is min-heap: push negative counts for max-heap, or use nlargest()",
        "Distributed merge: local top-K per node doesn't guarantee global top-K — you need global counts"
      ]
    },
    "sortOrder": 44
  },
  {
    "id": "scenario-dedup",
    "track": "coding",
    "name": "Deduplicate Events Within Time Window",
    "prompt": "Each event has (event_id, timestamp). Remove duplicates where the same event_id occurs within T seconds of a previous accepted occurrence. Return the deduplicated list.",
    "difficulty": "Medium",
    "priority": "TOP",
    "tags": [
      "sliding-window",
      "hashmap",
      "idempotency",
      "streaming"
    ],
    "companies": [],
    "content": {
      "why": "Exactly-once semantics and deduplication are core to streaming pipelines. This tests whether you understand idempotency at scale.",
      "approach": [
        "Sort events by timestamp if not already sorted — O(n log n)",
        "Maintain last_accepted = {} mapping event_id → timestamp of last accepted event",
        "For each event: if event_id not in last_accepted OR ts - last_accepted[event_id] > T → accept and update",
        "Return accepted events in order",
        "Space: O(unique event_ids) for the map"
      ],
      "followUps": [
        "What if the same event_id can appear in different partitions (distributed input)?",
        "How do you handle events that arrive out of order (late data)?",
        "What if T is a sliding calendar window (not fixed seconds)?",
        "How would you implement this in a stateful streaming framework (Spark Structured Streaming)?"
      ],
      "gotchas": [
        "If input is unsorted: sort by timestamp FIRST — the order matters for 'within T seconds'",
        "Boundary: is exactly T seconds a duplicate? Clarify: 'within T' vs 'within T inclusive'",
        "Late data: if events arrive out of order, you need a watermark mechanism — mention it even if not asked"
      ]
    },
    "sortOrder": 45
  },
  {
    "id": "scenario-session",
    "track": "coding",
    "name": "Sessionize Clickstream",
    "prompt": "Given user click events as (user_id, timestamp) sorted by timestamp, break each user's events into sessions where a new session starts when the gap between consecutive events exceeds G seconds. Return total session count and duration per session.",
    "difficulty": "Medium",
    "priority": "HIGH",
    "tags": [
      "sorting",
      "aggregation",
      "sessionization",
      "analytics"
    ],
    "companies": [],
    "content": {
      "why": "Sessionization is a fundamental analytics transformation in data engineering, run at massive scale in distributed systems.",
      "approach": [
        "Group events by user_id — use defaultdict(list) or sort by (user_id, timestamp)",
        "For each user's events (sorted): walk linearly, track session_start and prev_ts",
        "If ts - prev_ts > G: close current session (duration = prev_ts - session_start), start new",
        "After loop: close the last open session",
        "Return list of (user_id, session_start, session_end, duration)"
      ],
      "followUps": [
        "What if events aren't sorted by timestamp within each user?",
        "How do you compute session duration if events have explicit durations vs just timestamps?",
        "Distributed version: events for same user spread across partitions — how do you handle session boundaries at partition edges?",
        "What if G is different per user (configurable)?"
      ],
      "gotchas": [
        "Don't forget to close the LAST session after the loop — easy miss",
        "Single-event sessions are valid: session_start = session_end = that event's timestamp",
        "Duration = last_event_ts - first_event_ts (not counting from gap boundary to gap boundary)"
      ]
    },
    "sortOrder": 46
  },
  {
    "id": "scenario-components",
    "track": "coding",
    "name": "Connected Components with Heavy Nodes",
    "prompt": "Given an undirected graph, return the list of connected components (as sets of nodes). Some nodes are 'heavy' with very high degree. Ensure your solution remains efficient under skewed degree distribution.",
    "difficulty": "Medium",
    "priority": "HIGH",
    "tags": [
      "union-find",
      "graph",
      "data-skew",
      "O(alpha)"
    ],
    "companies": [],
    "content": {
      "why": "File metadata graphs can have highly skewed degree distributions (one table with thousands of partitions). Naive BFS degrades badly; Union-Find doesn't.",
      "approach": [
        "Union-Find with path compression + union by rank — near O(1) per operation",
        "For each edge (u, v): call union(u, v)",
        "Find all roots: for each node, find(node) gives its component ID",
        "Group nodes by root → connected components",
        "DO NOT use naive BFS/DFS per node — O(V+E) total is fine but the heavy-node comment is a hint to use UF"
      ],
      "followUps": [
        "What if edges are added incrementally (online)? Union-Find handles this naturally.",
        "What if you also need to remove edges (decremental connectivity)? Much harder — link-cut trees.",
        "How many components? Just count distinct roots after all unions.",
        "Weighted version: find if two nodes are in the same component with minimum path weight."
      ],
      "gotchas": [
        "Path compression: parent[x] = find(parent[x]) — recursive assignment, not just return",
        "Union by rank: always attach smaller tree under larger — prevents O(n) chain",
        "Without both optimizations, Union-Find degrades to O(n) per operation on adversarial input"
      ]
    },
    "sortOrder": 47
  },
  {
    "id": "scenario-lrucache",
    "track": "coding",
    "name": "LRU Cache / Time-Bounded Cache",
    "prompt": "Implement an LRU cache with get(key) and put(key, value). Both O(1). Follow-up: add TTL — entries expire after T seconds.",
    "difficulty": "Medium",
    "priority": "HIGH",
    "tags": [
      "design",
      "doubly-linked-list",
      "hashmap",
      "O(1)"
    ],
    "companies": [],
    "content": {
      "why": "Caching is pervasive in data systems (query result cache, block cache, metadata cache). LRU + TTL tests your ability to combine data structures.",
      "approach": [
        "HashMap of key → node for O(1) lookup",
        "Doubly linked list for O(1) move-to-front (most recent) and evict-from-tail (least recent)",
        "Dummy head and tail nodes eliminate edge cases on empty list",
        "get: lookup in map, move node to head, return value",
        "put: if exists → update + move to head. If not → create at head. If over capacity → evict tail, remove from map",
        "TTL follow-up: store (value, expiry_ts) in node. On get: check if expired → treat as miss + remove"
      ],
      "followUps": [
        "Add TTL: entries expire after T seconds. How does this change get() and put()?",
        "Thread-safe version: add a lock. What's the granularity — one global lock or per-shard?",
        "LFU Cache: least frequently used eviction instead of least recently used (harder)",
        "How would you implement this distributed across multiple nodes?"
      ],
      "gotchas": [
        "Implement the doubly linked list yourself — using Python's OrderedDict shortcuts the learning",
        "Dummy head/tail: head.next = MRU, tail.prev = LRU — remove_node and add_to_front are symmetric",
        "TTL: check expiry in get() AND in put() (to avoid returning expired values or updating expired keys)"
      ]
    },
    "sortOrder": 48
  },
  {
    "id": "scenario-streammedian",
    "track": "coding",
    "name": "Streaming Median with Memory Constraint",
    "prompt": "Design a data structure that accepts a stream of integers and returns the running median after each insertion. Follow-up: the stream is partitioned — compute per-partition medians, then merge approximate global median.",
    "difficulty": "Hard",
    "priority": "HIGH",
    "tags": [
      "two-heaps",
      "streaming",
      "median",
      "memory-aware"
    ],
    "companies": [],
    "content": {
      "why": "Percentile/median computation over large data streams is a core analytics primitive. Production systems use approximate algorithms (t-digest) at scale.",
      "approach": [
        "Two heaps: max-heap (lower half) and min-heap (upper half)",
        "Invariant: lower.size >= upper.size, lower.size - upper.size <= 1",
        "Add: push to lower (max-heap, negate). Rebalance: if lower.top > upper.top, move lower.top to upper. If sizes imbalanced, rebalance.",
        "Median: if lower.size > upper.size → -lower[0]. Else average of both tops.",
        "Follow-up: per-partition medians don't combine to global median — mention t-digest or reservoir sampling"
      ],
      "followUps": [
        "What's the exact median vs approximate median trade-off?",
        "t-digest sketch: how does it give approximate quantiles with bounded error?",
        "If you have per-partition medians, can you compute the global median exactly? (No, in general)",
        "How does Spark's approxQuantile work under the hood?"
      ],
      "gotchas": [
        "Python heapq is min-heap — negate all values for the max-heap (lower half)",
        "Rebalance AFTER every insert — don't batch rebalancing",
        "Equal sizes → average of both tops. Lower larger → -lower[0]. Never upper larger."
      ]
    },
    "sortOrder": 49
  },
  {
    "id": "sd-news_agg",
    "track": "system_design",
    "name": "News Aggregator (Google News)",
    "prompt": "Design a news aggregation system that ingests articles from thousands of publishers, deduplicates stories, ranks them, and serves personalized feeds to users.",
    "difficulty": "Hard",
    "tags": [
      "ingestion",
      "ranking",
      "caching",
      "dedup",
      "scaling"
    ],
    "companies": [],
    "content": {
      "category": "Data-Intensive",
      "tier": 1,
      "keyComponents": [
        "Ingestion: RSS/webhook crawlers → Kafka → normalize → dedup (SimHash) → store",
        "Storage: Article metadata in Postgres, content in object store, search index in Elasticsearch",
        "Feed generation: Pull model + caching. Pre-compute popular topics, on-demand for personalized",
        "Ranking: Recency + source quality + topic relevance. ML re-ranking as future state",
        "Dedup: Same story from 50 outlets — cluster by content similarity (SimHash/MinHash)",
        "Caching: CDN for static, Redis for user feeds, stale-while-revalidate",
        "Scaling: Separate read/write, partition by topic/region, cache aggressively"
      ],
      "deepDive": [
        "How do you handle a breaking news spike where 1000 sources publish the same story in 5 min?",
        "Pull vs push for feed generation — what are the trade-offs at 10M DAU?",
        "How do you balance freshness vs relevance in ranking?",
        "What happens if your Kafka consumer falls behind during a spike?"
      ],
      "monitoring": [
        "Ingestion lag (time from publish to indexed)",
        "Feed freshness (p95 article age on homepage)",
        "Dedup precision/recall (are we clustering correctly?)",
        "Cache hit ratio on feed endpoint",
        "Error rates by publisher source"
      ]
    },
    "sortOrder": 50
  },
  {
    "id": "sd-doc_verify",
    "track": "system_design",
    "name": "Document Verification System",
    "prompt": "Design a system to upload employee documents, assign them for manual verification with SLA-based priority, and track verification status. 500K docs/day, SLA 1-4 hours.",
    "difficulty": "Hard",
    "tags": [
      "async",
      "SLA",
      "ticketing",
      "multi-tenant",
      "batch"
    ],
    "companies": [],
    "content": {
      "category": "Workflow",
      "tier": 1,
      "keyComponents": [
        "Upload API → S3 (binary) + Postgres metadata (employeeId, orgId, docType, status)",
        "Async queue → priority-based routing to human reviewer pool",
        "SLA engine: ticket priority auto-escalates as deadline approaches",
        "Status API: simple DB read, low frequency — no caching needed",
        "Multi-tenant: orgId in every query, row-level security or schema isolation",
        "Bulk processing: fan-out via queue with many consumers"
      ],
      "deepDive": [
        "How do you prevent the same document being assigned to two reviewers?",
        "What happens if a reviewer's session expires mid-review?",
        "How do you handle SLA breach — auto-escalation? Alert? Reassign?",
        "Bulk upload of 10K docs for a new company onboarding — how does the system handle it?"
      ],
      "monitoring": [
        "SLA compliance % (by doc type, by org)",
        "Queue depth and wait time",
        "Reviewer throughput (docs/hour)",
        "Upload failure rate",
        "p95 time-to-first-review"
      ]
    },
    "sortOrder": 51
  },
  {
    "id": "sd-news_feed",
    "track": "system_design",
    "name": "News Feed System",
    "prompt": "Design a social media news feed system that shows personalized posts from followed users. Scale to ~1M users.",
    "difficulty": "Hard",
    "tags": [
      "fan-out",
      "ranking",
      "caching",
      "pub-sub",
      "denormalization"
    ],
    "companies": [],
    "content": {
      "category": "Data-Intensive",
      "tier": 1,
      "keyComponents": [
        "Fan-out-on-write (push) for normal users, fan-out-on-read (pull) for celebrities",
        "Feed cache in Redis: pre-built per user, invalidated on new posts",
        "Ranking: chronological baseline + engagement signals",
        "Social graph: follower relationships in graph DB or adjacency list",
        "Media: separate object store + CDN for images/video"
      ],
      "deepDive": [
        "Celebrity problem: user with 10M followers posts — how do you handle fan-out?",
        "How do you handle a user scrolling to load older feed items (pagination)?",
        "What's the cache invalidation strategy when someone you follow posts?",
        "How do you inject ads or promoted content into the feed?"
      ],
      "monitoring": [
        "Feed generation latency (p50/p95)",
        "Fan-out lag for celebrity posts",
        "Cache hit ratio on feed reads",
        "Post-to-visible latency (time from publish to appearing in follower feeds)"
      ]
    },
    "sortOrder": 52
  },
  {
    "id": "sd-metrics_mon",
    "track": "system_design",
    "name": "Metrics Monitoring System",
    "prompt": "Design a metrics monitoring and alerting system that ingests billions of data points per day, supports dashboards, and fires alerts on anomalies.",
    "difficulty": "Medium",
    "tags": [
      "time-series",
      "TSDB",
      "alerting",
      "aggregation",
      "dashboards"
    ],
    "companies": [],
    "content": {
      "category": "Infrastructure",
      "tier": 2,
      "keyComponents": [
        "Ingestion: agents → Kafka → stream processor (window aggregation) → TSDB",
        "Storage: ClickHouse or TimescaleDB for hot data, S3 for cold (downsampled)",
        "Query layer: pre-aggregated rollups (1m, 5m, 1h) for dashboard performance",
        "Alerting: rules engine evaluates thresholds on aggregated data, fires to PagerDuty/Slack",
        "Retention: raw 7d → 1m agg 30d → 1h agg 1yr → archive"
      ],
      "deepDive": [
        "How do you handle late-arriving data points?",
        "Downsampling strategy: what do you lose and how do you mitigate?",
        "How do you avoid alert storms (1000 hosts all breach threshold at once)?",
        "Push vs pull model for metric collection — trade-offs?"
      ],
      "monitoring": [
        "Ingestion throughput (data points/sec)",
        "Query latency for dashboard renders",
        "Alert evaluation latency",
        "Data loss rate (dropped metrics)"
      ]
    },
    "sortOrder": 53
  },
  {
    "id": "sd-expense_rules",
    "track": "system_design",
    "name": "Corporate Expense Rules Engine",
    "prompt": "Design a rules engine for corporate expense management. Companies define policies (e.g., meals < $50, flights need manager approval), and the system evaluates expenses against them.",
    "difficulty": "Medium",
    "tags": [
      "rules-engine",
      "policy",
      "multi-tenant",
      "workflow",
      "approval"
    ],
    "companies": [],
    "content": {
      "category": "Payments & Trust",
      "tier": 2,
      "keyComponents": [
        "Rule DSL: condition → action pairs, composable (AND/OR), per-tenant",
        "Evaluation engine: expenses evaluated against tenant's active rule set",
        "Actions: auto-approve, flag-for-review, reject, route-to-approver",
        "Approval chain: leverages org hierarchy (manager, director, VP)",
        "Version control: rules are versioned, old expenses evaluated against point-in-time rules"
      ],
      "deepDive": [
        "How do you handle rule conflicts (one rule says approve, another says reject)?",
        "How do you test a rule change before deploying it to production?",
        "Performance: 10K expenses submitted at month-end — how fast does evaluation need to be?",
        "How do you audit which rule was responsible for a decision?"
      ],
      "monitoring": [
        "Rule evaluation latency per expense",
        "Approval queue depth by tenant",
        "False positive rate (flagged expenses that are actually fine)",
        "Rule version adoption across tenants"
      ]
    },
    "sortOrder": 54
  },
  {
    "id": "sd-employee_lifecycle",
    "track": "system_design",
    "name": "Employee Lifecycle Event Propagation",
    "prompt": "Design a system where employee changes (hired, promoted, terminated, dept change) propagate reliably to dozens of downstream systems (payroll, IT provisioning, benefits, etc.).",
    "difficulty": "Advanced",
    "tags": [
      "event-driven",
      "SCIM",
      "SAML",
      "multi-tenant",
      "idempotency"
    ],
    "companies": [],
    "content": {
      "category": "Platform",
      "tier": 3,
      "keyComponents": [
        "Employee Graph: single source of truth (Postgres + CDC)",
        "Event bus: Kafka — every mutation publishes typed event",
        "Consumers: Payroll, IT provisioning (SCIM to Slack/Google), Benefits, Device mgmt",
        "Ordering: per-employee via Kafka partition key = employeeId",
        "Idempotency: each consumer tracks last processed offset per entity",
        "DLQ: failed propagations → retry with backoff → alert on persistent failure",
        "Audit log: immutable event store for compliance"
      ],
      "deepDive": [
        "Employee is terminated — what's the order of operations? (Revoke access first, then payroll)",
        "How do you handle a 3rd-party integration that's down for 2 hours?",
        "How do you handle schema evolution as new fields are added to employee events?",
        "Multi-tenant isolation: how do you prevent one tenant's event storm from blocking others?"
      ],
      "monitoring": [
        "Propagation latency (event published → all consumers acknowledged)",
        "Consumer lag per downstream system",
        "DLQ depth and age of oldest message",
        "Integration health per 3rd party (success rate, latency)"
      ]
    },
    "sortOrder": 55
  }
];
